---

# plugins: [flowtype]

plugins:
  - jest

env:
    node: true
    jest: true
    jasmine: true

parser: babel-eslint

extends:
    - 'airbnb-base'
    - 'plugin:jest/recommended'

rules:
    global-require: 0
    no-unused-vars: 0


